In [1]:
import pandas as pd,numpy as np

In [6]:
df = pd.read_csv("../data/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
df.shape

(7043, 21)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [11]:
df['TotalCharges'].isnull().sum()

11

In [14]:
df.loc[df['TotalCharges'].isnull(), ['tenure']]

      tenure
488        0
753        0
936        0
1082       0
1340       0
3331       0
3826       0
4380       0
5218       0
6670       0
6754       0

In [ ]:
df.loc[(df['TotalCharges'].isnull()) ,['Churn']]

     Churn
488     No
753     No
936     No
1082    No
1340    No
3331    No
3826    No
4380    No
5218    No
6670    No
6754    No

In [21]:
df.dropna(subset=['TotalCharges'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [24]:
total_churn = df[df['Churn'] == 'Yes'].shape[0]
total_churn

1869

In [25]:
churn_rate = total_churn / df.shape[0]
churn_rate

0.26578498293515357

In [26]:
churn_by_gender = df.groupby('gender')['Churn'].value_counts(normalize=True).unstack()
churn_by_gender

Churn         No       Yes
gender
Female  0.730405  0.269595
Male    0.737954  0.262046

In [27]:
churn_by_contract = df.groupby('Contract')['Churn'].value_counts(normalize=True).unstack()
churn_by_contract

Churn                 No       Yes
Contract
Month-to-month  0.572903  0.427097
One year        0.887228  0.112772
Two year        0.971513  0.028487

In [28]:
churn_by_senior_citizen = df.groupby('SeniorCitizen')['Churn'].value_counts(normalize=True).unstack()
churn_by_senior_citizen

Churn                No       Yes
SeniorCitizen
0              0.763497  0.236503
1              0.583187  0.416813

In [29]:
Total_revenue = df['TotalCharges'].sum()
Total_revenue

16056168.700000001

In [32]:
Revenue_by_churn = df.groupby('Churn')['TotalCharges'].sum()
Revenue_by_churn

Churn
No     13193241.8
Yes     2862926.9
Name: TotalCharges, dtype: float64

In [37]:
average_charges = df.groupby('Churn')['MonthlyCharges'].mean()
average_charges

Churn
No     61.307408
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [38]:
average_tenure = df.groupby('Churn')['tenure'].mean()
average_tenure

Churn
No     37.650010
Yes    17.979133
Name: tenure, dtype: float64

In [39]:
churn_by_internet_service = df.groupby('InternetService')['Churn'].value_counts(normalize=True).unstack()
churn_by_internet_service

Churn                  No       Yes
InternetService
DSL              0.810017  0.189983
Fiber optic      0.581072  0.418928
No               0.925658  0.074342

In [40]:
churn_by_payment_method = df.groupby('PaymentMethod')['Churn'].value_counts(normalize=True).unstack()
churn_by_payment_method

Churn                            No       Yes
PaymentMethod
Bank transfer (automatic)  0.832685  0.167315
Credit card (automatic)    0.847469  0.152531
Electronic check           0.547146  0.452854
Mailed check               0.807980  0.192020

In [46]:
#for tenure binning customers into 5 groups 
df['tenure_group'] = pd.cut(df['tenure'], bins=[0, 12, 24, 48, 60, 72], labels=['0-12', '12-24', '24-48', '48-60', '60-72'])
df['tenure_group']
churn_by_tenure_group = df.groupby('tenure_group')['Churn'].value_counts(normalize=True).unstack()
churn_by_tenure_group

C:\Users\123\AppData\Local\Temp\ipykernel_7948\3149004954.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  churn_by_tenure_group = df.groupby('tenure_group')['Churn'].value_counts(normalize=True).unstack()

Churn               No       Yes
tenure_group
0-12          0.523218  0.476782
12-24         0.712891  0.287109
24-48         0.796110  0.203890
48-60         0.855769  0.144231
60-72         0.933902  0.066098

In [45]:
#for monthly charges binning customers into 5 groups
df['monthly_charges_group'] = pd.cut(df['MonthlyCharges'], bins=[0, 20, 40, 60, 80, 100], labels=['0-20', '20-40', '40-60', '60-80', '80-100'])
df['monthly_charges_group']
churn_by_monthly_charges_group = df.groupby('monthly_charges_group')['Churn'].value_counts(normalize=True).unstack()
churn_by_monthly_charges_group

C:\Users\123\AppData\Local\Temp\ipykernel_7948\276226974.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  churn_by_monthly_charges_group = df.groupby('monthly_charges_group')['Churn'].value_counts(normalize=True).unstack()

Churn                        No       Yes
monthly_charges_group
0-20                   0.911179  0.088821
20-40                  0.867684  0.132316
40-60                  0.743970  0.256030
60-80                  0.675360  0.324640
80-100                 0.629609  0.370391

In [49]:
# -------------------------------------------------------------
# 1. Feature Engineering: Assigning Points based on Data Shapes
# -------------------------------------------------------------

# Tenure Score (Tiered cliff)
df["Score_Tenure"] = np.select(
    [df["tenure"] <= 12, (df["tenure"] > 12) & (df["tenure"] <= 24)],
    choicelist=[2, 1],
    default=0,
)

# Monthly Charges Score (Single accelerated threshold)
df["Score_Charges"] = np.where(df["MonthlyCharges"] >= 60, 1, 0)

# Contract Score (Highest risk for Month-to-Month)
df["Score_Contract"] = np.select(
    [df["Contract"] == "Month-to-month", df["Contract"] == "One year"],
    choicelist=[2, 1],
    default=0,
)

# Internet Service Score (Fiber optic friction)
df["Score_Internet"] = np.where(df["InternetService"] == "Fiber optic", 1, 0)

# Payment Method Score (Electronic check friction)
df["Score_Payment"] = np.where(df["PaymentMethod"] == "Electronic check", 1, 0)

# Senior Citizen Score
df["Score_Senior"] = np.where(df["SeniorCitizen"] == 1, 1, 0)

# -------------------------------------------------------------
# 2. Aggregate into Final Risk Score (Max possible score = 8)
# -------------------------------------------------------------
score_columns = [
    "Score_Tenure",
    "Score_Charges",
    "Score_Contract",
    "Score_Internet",
    "Score_Payment",
    "Score_Senior",
]
df["RiskScore"] = df[score_columns].sum(axis=1)

# -------------------------------------------------------------
# 3. Validation: Does the score cleanly correlate with Churn?
# -------------------------------------------------------------
# Assumes 'Churn' column is binary (1 for Churn, 0 for Retained)
if df["Churn"].dtype == "object":
    df["Churn"] = np.where(df["Churn"].str.lower() == "yes", 1, 0)

validation_table = (
    df.groupby("RiskScore")
    .agg(Total_Customers=("Churn", "count"), Churned_Customers=("Churn", "sum"))
    .reset_index()
)

# Calculate real-world churn rate per risk tier
validation_table["Actual_Churn_Rate"] = (
    validation_table["Churned_Customers"] / validation_table["Total_Customers"]
) * 100

# Display the validation matrix
print(validation_table.to_string(index=False))

 RiskScore  Total_Customers  Churned_Customers  Actual_Churn_Rate
         0              592                  7           1.182432
         1              816                 12           1.470588
         2              958                 76           7.933194
         3              888                102          11.486486
         4             1381                374          27.081825
         5              917                354          38.604144
         6              704                401          56.960227
         7              605                418          69.090909
         8              171                125          73.099415

In [53]:
# -------------------------------------------------------------
# 4. Create Contact List (Active Customers Only)
# -------------------------------------------------------------

# Keep only customers who have NOT churned
active_customers = df[df["Churn"] == 0].copy()

# -------------------------------------------------------------
# 5. Assign Risk Tiers
# -------------------------------------------------------------
active_customers["RiskTier"] = np.select(
    [
        active_customers["RiskScore"] >= 6,
        active_customers["RiskScore"].between(4, 5),
        active_customers["RiskScore"].between(0, 3),
    ],
    [
        "call this week",
        "call this month",
        "monitor",
    ]
)

# -------------------------------------------------------------
# 6. Sort Highest-Risk Customers First
# -------------------------------------------------------------
active_customers = active_customers.sort_values(
    by=["RiskScore", "tenure"],
    ascending=[False, True]
)

# Preview contact list
print(
    active_customers[
        [
            "customerID",
            "RiskScore",
            "RiskTier",
            "tenure",
            "MonthlyCharges",
            "Contract",
        ]
    ].head(10)
)

      customerID  RiskScore        RiskTier  tenure  MonthlyCharges  \
91    2424-WVHPL          8  call this week       1           74.70
345   0021-IKXGC          8  call this week       1           72.10
2036  8775-ERLNB          8  call this week       1           74.30
2422  9603-OAIHC          8  call this week       1           70.05
3633  3878-AVSOQ          8  call this week       1           71.25
6096  9605-WGJVW          8  call this week       1           70.20
3346  2545-EBUPK          8  call this week       2           84.05
3497  9799-CAYJJ          8  call this week       2           69.30
3529  2880-FPNAE          8  call this week       2           74.20
6411  5119-NZPTV          8  call this week       2           70.10

            Contract
91    Month-to-month
345   Month-to-month
2036  Month-to-month
2422  Month-to-month
3633  Month-to-month
6096  Month-to-month
3346  Month-to-month
3497  Month-to-month
3529  Month-to-month
6411  Month-to-month

In [54]:
# -------------------------------------------------------------
# 7. Count Customers in Each Tier
# -------------------------------------------------------------

tier_counts = (
    active_customers["RiskTier"]
    .value_counts()
    .reindex(
        ["call this week", "call this month", "monitor"],
        fill_value=0
    )
    .reset_index()
)

tier_counts.columns = ["RiskTier", "Customers"]

print(tier_counts.to_string(index=False))

       RiskTier  Customers
 call this week        536
call this month       1570
        monitor       3057

In [56]:
#pull 5 to 10 rows from call this week tier
call_this_week_customers = active_customers[active_customers["RiskTier"] == "call this week"].head(10)
print(call_this_week_customers[["customerID", "RiskScore", "tenure", "MonthlyCharges", "Contract","PaymentMethod","InternetService"]].to_string(index=False))

customerID  RiskScore  tenure  MonthlyCharges       Contract    PaymentMethod InternetService
2424-WVHPL          8       1           74.70 Month-to-month Electronic check     Fiber optic
0021-IKXGC          8       1           72.10 Month-to-month Electronic check     Fiber optic
8775-ERLNB          8       1           74.30 Month-to-month Electronic check     Fiber optic
9603-OAIHC          8       1           70.05 Month-to-month Electronic check     Fiber optic
3878-AVSOQ          8       1           71.25 Month-to-month Electronic check     Fiber optic
9605-WGJVW          8       1           70.20 Month-to-month Electronic check     Fiber optic
2545-EBUPK          8       2           84.05 Month-to-month Electronic check     Fiber optic
9799-CAYJJ          8       2           69.30 Month-to-month Electronic check     Fiber optic
2880-FPNAE          8       2           74.20 Month-to-month Electronic check     Fiber optic
5119-NZPTV          8       2           70.10 Month-to-month Electronic check     Fiber optic

In [57]:
#make csv file of the active customers active_customers (with the columns that matter: customerID, RiskScore, RiskTier, tenure, MonthlyCharges, Contract, InternetService, PaymentMethod
active_customers[["customerID", "RiskScore", "RiskTier", "tenure", "MonthlyCharges", "Contract", "InternetService", "PaymentMethod"]].to_csv("../data/active_customers_with_risk_scores.csv", index=False)